import type { FieldAccess, PermissionProject } from "./types";

const bool = (value: boolean): "1" | "0" => (value ? "1" : "0");

export function generateAccessCsv(project: PermissionProject): string {
  const rows = ["id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink"];
  for (const model of project.models) {
    for (const role of project.roles) {
      const access = model.accessByRole[role.id];
      rows.push(
        [
          `access_${model.id}_${role.id}`,
          `${model.name} / ${role.name}`,
          `model_${model.technicalName.replaceAll(".", "_")}`,
          `your_module.${role.technicalName}`,
          bool(access.read),
          bool(access.write),
          bool(access.create),
          bool(access.unlink),
        ].join(","),
      );
    }
  }
  return rows.join("\n");
}

export function generateRecordRulesXml(project: PermissionProject): string {
  const records = project.models.flatMap((model) =>
    project.roles.map((role) => {
      const domain = model.recordScopeByRole[role.id] || "[(1, '=', 1)]";
      const access = model.accessByRole[role.id];
      return `  <record id="rule_${model.id}_${role.id}" model="ir.rule">
    <field name="name">${model.name} / ${role.name}</field>
    <field name="model_id" ref="model_${model.technicalName.replaceAll(".", "_")}"/>
    <field name="groups" eval="[(4, ref('your_module.${role.technicalName}'))]"/>
    <field name="domain_force">${escapeXml(domain)}</field>
    <field name="perm_read" eval="${pyBool(access.read)}"/>
    <field name="perm_write" eval="${pyBool(access.write)}"/>
    <field name="perm_create" eval="${pyBool(access.create)}"/>
    <field name="perm_unlink" eval="${pyBool(access.unlink)}"/>
  </record>`;
    }),
  );

  return `<?xml version="1.0" encoding="utf-8"?>
<odoo>
${records.join("\n\n")}
</odoo>`;
}

export function generateFieldSecurityNotes(project: PermissionProject): string {
  const lines: string[] = [
    "# Field security plan generated by Odoo Permission Designer",
    "# Apply hard field restrictions with the ORM field `groups` attribute.",
    "",
  ];

  for (const model of project.models) {
    lines.push(`# ${model.name} (${model.technicalName})`);
    for (const field of model.fields) {
      const visibleRoles = project.roles
        .filter((role) => field.accessByRole[role.id] !== "hidden")
        .map((role) => `your_module.${role.technicalName}`);
      const editableRoles = project.roles
        .filter((role) => field.accessByRole[role.id] === "editable")
        .map((role) => role.name);
      lines.push(
        `${field.technicalName}: groups=${JSON.stringify(visibleRoles.join(","))}  # editable: ${editableRoles.join("、") || "none"}`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function fieldAccessLabel(value: FieldAccess): string {
  return {
    hidden: "隐藏",
    readonly: "只读",
    editable: "可编辑",
    masked: "脱敏",
  }[value];
}

function pyBool(value: boolean): "True" | "False" {
  return value ? "True" : "False";
}

function escapeXml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}
