import type { AccessRights, FieldAccess, PermissionProject } from "./types";

const crud = (
  read: boolean,
  create: boolean,
  write: boolean,
  unlink: boolean,
): AccessRights => ({ read, create, write, unlink });

const fieldAccess = (
  sales: FieldAccess,
  manager: FieldAccess,
  finance: FieldAccess,
  warehouse: FieldAccess,
): Record<string, FieldAccess> => ({ sales, manager, finance, warehouse });

export const initialPermissionProject: PermissionProject = {
  id: "odoo-access-studio-demo",
  name: "Odoo 销售订单权限设计",
  odooVersion: "19.0",
  roles: [
    { id: "sales", name: "销售人员", technicalName: "group_sale_user" },
    {
      id: "manager",
      name: "销售经理",
      technicalName: "group_sale_manager",
    },
    { id: "finance", name: "财务人员", technicalName: "group_account_user" },
    { id: "warehouse", name: "仓库人员", technicalName: "group_stock_user" },
  ],
  users: [
    {
      id: "john",
      name: "John Smith",
      email: "john@example.com",
      company: "US Company",
      roleIds: ["sales"],
    },
    {
      id: "sarah",
      name: "Sarah Miller",
      email: "sarah@example.com",
      company: "US Company",
      roleIds: ["manager"],
    },
    {
      id: "emma",
      name: "Emma Davis",
      email: "emma@example.com",
      company: "US Company",
      roleIds: ["finance"],
    },
  ],
  models: [
    {
      id: "partner",
      name: "客户",
      technicalName: "res.partner",
      module: "Contacts",
      position: { x: 270, y: 42 },
      accessByRole: {
        sales: crud(true, true, true, false),
        manager: crud(true, true, true, true),
        finance: crud(true, false, false, false),
        warehouse: crud(true, false, false, false),
      },
      recordScopeByRole: {
        sales: "['|', ('user_id', '=', user.id), ('create_uid', '=', user.id)]",
        manager: "[('team_id.member_ids', 'in', user.id)]",
        finance: "[(1, '=', 1)]",
        warehouse: "[('customer_rank', '>', 0)]",
      },
      fields: [
        {
          id: "partner_name",
          name: "客户名称",
          technicalName: "name",
          fieldType: "char",
          accessByRole: fieldAccess("editable", "editable", "readonly", "readonly"),
        },
        {
          id: "partner_phone",
          name: "电话",
          technicalName: "phone",
          fieldType: "char",
          accessByRole: fieldAccess("editable", "editable", "masked", "hidden"),
        },
        {
          id: "partner_credit",
          name: "信用额度",
          technicalName: "credit_limit",
          fieldType: "monetary",
          accessByRole: fieldAccess("hidden", "readonly", "editable", "hidden"),
        },
      ],
    },
    {
      id: "sale_order",
      name: "销售订单",
      technicalName: "sale.order",
      module: "Sales",
      position: { x: 530, y: 190 },
      accessByRole: {
        sales: crud(true, true, true, false),
        manager: crud(true, true, true, true),
        finance: crud(true, false, false, false),
        warehouse: crud(true, false, false, false),
      },
      recordScopeByRole: {
        sales: "[('user_id', '=', user.id)]",
        manager: "[('team_id.member_ids', 'in', user.id)]",
        finance: "[(1, '=', 1)]",
        warehouse: "[('state', 'in', ['sale', 'done'])]",
      },
      fields: [
        {
          id: "order_partner",
          name: "客户",
          technicalName: "partner_id",
          fieldType: "many2one",
          relation: "res.partner",
          accessByRole: fieldAccess("editable", "editable", "readonly", "readonly"),
        },
        {
          id: "order_amount",
          name: "销售金额",
          technicalName: "amount_total",
          fieldType: "monetary",
          accessByRole: fieldAccess("editable", "editable", "readonly", "readonly"),
        },
        {
          id: "order_margin",
          name: "毛利率",
          technicalName: "margin_percent",
          fieldType: "float",
          accessByRole: fieldAccess("hidden", "readonly", "readonly", "hidden"),
        },
        {
          id: "order_state",
          name: "状态",
          technicalName: "state",
          fieldType: "selection",
          accessByRole: fieldAccess("readonly", "readonly", "readonly", "readonly"),
        },
      ],
    },
    {
      id: "invoice",
      name: "客户发票",
      technicalName: "account.move",
      module: "Accounting",
      position: { x: 800, y: 48 },
      accessByRole: {
        sales: crud(true, false, false, false),
        manager: crud(true, false, false, false),
        finance: crud(true, true, true, true),
        warehouse: crud(false, false, false, false),
      },
      recordScopeByRole: {
        sales: "[('invoice_user_id', '=', user.id)]",
        manager: "[('invoice_user_id.team_id.member_ids', 'in', user.id)]",
        finance: "[('company_id', 'in', company_ids)]",
        warehouse: "[(0, '=', 1)]",
      },
      fields: [
        {
          id: "invoice_partner",
          name: "客户",
          technicalName: "partner_id",
          fieldType: "many2one",
          relation: "res.partner",
          accessByRole: fieldAccess("readonly", "readonly", "editable", "hidden"),
        },
        {
          id: "invoice_amount",
          name: "发票金额",
          technicalName: "amount_total",
          fieldType: "monetary",
          accessByRole: fieldAccess("readonly", "readonly", "editable", "hidden"),
        },
        {
          id: "invoice_payment",
          name: "付款状态",
          technicalName: "payment_state",
          fieldType: "selection",
          accessByRole: fieldAccess("readonly", "readonly", "editable", "hidden"),
        },
      ],
    },
    {
      id: "picking",
      name: "交付单",
      technicalName: "stock.picking",
      module: "Inventory",
      position: { x: 300, y: 365 },
      accessByRole: {
        sales: crud(true, false, false, false),
        manager: crud(true, false, false, false),
        finance: crud(false, false, false, false),
        warehouse: crud(true, true, true, false),
      },
      recordScopeByRole: {
        sales: "[('sale_id.user_id', '=', user.id)]",
        manager: "[('sale_id.team_id.member_ids', 'in', user.id)]",
        finance: "[(0, '=', 1)]",
        warehouse: "[('company_id', 'in', company_ids)]",
      },
      fields: [
        {
          id: "picking_origin",
          name: "来源单据",
          technicalName: "origin",
          fieldType: "char",
          accessByRole: fieldAccess("readonly", "readonly", "hidden", "readonly"),
        },
        {
          id: "picking_partner",
          name: "交付地址",
          technicalName: "partner_id",
          fieldType: "many2one",
          relation: "res.partner",
          accessByRole: fieldAccess("readonly", "readonly", "hidden", "editable"),
        },
        {
          id: "picking_state",
          name: "状态",
          technicalName: "state",
          fieldType: "selection",
          accessByRole: fieldAccess("readonly", "readonly", "hidden", "editable"),
        },
      ],
    },
  ],
  workflow: {
    model: "sale.order",
    states: [
      { id: "draft", name: "草稿", technicalValue: "draft", x: 55, y: 150 },
      { id: "sent", name: "已报价", technicalValue: "sent", x: 245, y: 150 },
      { id: "approval", name: "待审批", technicalValue: "approval", x: 435, y: 150 },
      { id: "sale", name: "已确认", technicalValue: "sale", x: 625, y: 150 },
      { id: "done", name: "已完成", technicalValue: "done", x: 815, y: 150 },
    ],
    transitions: [
      {
        id: "send_quote",
        name: "发送报价",
        from: "draft",
        to: "sent",
        allowedRoleIds: ["sales", "manager"],
        condition: "订单至少包含一个产品行",
        actions: ["发送报价邮件", "记录报价时间"],
      },
      {
        id: "request_approval",
        name: "提交审批",
        from: "sent",
        to: "approval",
        allowedRoleIds: ["sales", "manager"],
        condition: "订单金额 > 100000 或折扣 > 15%",
        actions: ["创建审批活动", "通知销售经理"],
      },
      {
        id: "approve_order",
        name: "批准订单",
        from: "approval",
        to: "sale",
        allowedRoleIds: ["manager"],
        condition: "客户信用状态正常",
        actions: ["锁定销售价格", "创建交付单", "通知仓库"],
      },
      {
        id: "complete_order",
        name: "完成订单",
        from: "sale",
        to: "done",
        allowedRoleIds: ["manager", "warehouse", "finance"],
        condition: "交付完成且发票已过账",
        actions: ["写入完成时间"],
      },
    ],
  },
};
