import type { AccessRights, FieldAccess, PermissionProject } from "./types";

const crud = (
  read: boolean,
  create: boolean,
  write: boolean,
  unlink: boolean,
): AccessRights => ({ read, create, write, unlink });

const fieldAccess = (
  sales: FieldAccess,
  manager: FieldAccess,
  finance: FieldAccess,
  warehouse: FieldAccess,
): Record<string, FieldAccess> => ({ sales, manager, finance, warehouse });

export const initialPermissionProject: PermissionProject = {
  id: "odoo-access-studio-demo",
  name: "Odoo Sales Order Permission Design",
  odooVersion: "19.0",
  roles: [
    { id: "sales", name: "Sales Person", technicalName: "group_sale_user" },
    {
      id: "manager",
      name: "Sales Manager",
      technicalName: "group_sale_manager",
    },
    { id: "finance", name: "Accountant", technicalName: "group_account_user" },
    { id: "warehouse", name: "Warehouse Staff", technicalName: "group_stock_user" },
  ],
  users: [
    {
      id: "john",
      name: "John Smith",
      email: "john@example.com",
      company: "US Company",
      roleIds: ["sales"],
    },
    {
      id: "sarah",
      name: "Sarah Miller",
      email: "sarah@example.com",
      company: "US Company",
      roleIds: ["manager"],
    },
    {
      id: "emma",
      name: "Emma Davis",
      email: "emma@example.com",
      company: "US Company",
      roleIds: ["finance"],
    },
  ],
  models: [
    {
      id: "partner",
      name: "Customer",
      technicalName: "res.partner",
      module: "Contacts",
      position: { x: 270, y: 42 },
      accessByRole: {
        sales: crud(true, true, true, false),
        manager: crud(true, true, true, true),
        finance: crud(true, false, false, false),
        warehouse: crud(true, false, false, false),
      },
      recordScopeByRole: {
        sales: "['|', ('user_id', '=', user.id), ('create_uid', '=', user.id)]",
        manager: "[('team_id.member_ids', 'in', user.id)]",
        finance: "[(1, '=', 1)]",
        warehouse: "[('customer_rank', '>', 0)]",
      },
      fields: [
        {
          id: "partner_name",
          name: "Customer Name",
          technicalName: "name",
          fieldType: "char",
          accessByRole: fieldAccess("editable", "editable", "readonly", "readonly"),
        },
        {
          id: "partner_phone",
          name: "Phone",
          technicalName: "phone",
          fieldType: "char",
          accessByRole: fieldAccess("editable", "editable", "masked", "hidden"),
        },
        {
          id: "partner_credit",
          name: "Credit Limit",
          technicalName: "credit_limit",
          fieldType: "monetary",
          accessByRole: fieldAccess("hidden", "readonly", "editable", "hidden"),
        },
      ],
    },
    {
      id: "sale_order",
      name: "Sales Order",
      technicalName: "sale.order",
      module: "Sales",
      position: { x: 530, y: 190 },
      accessByRole: {
        sales: crud(true, true, true, false),
        manager: crud(true, true, true, true),
        finance: crud(true, false, false, false),
        warehouse: crud(true, false, false, false),
      },
      recordScopeByRole: {
        sales: "[('user_id', '=', user.id)]",
        manager: "[('team_id.member_ids', 'in', user.id)]",
        finance: "[(1, '=', 1)]",
        warehouse: "[('state', 'in', ['sale', 'done'])]",
      },
      fields: [
        {
          id: "order_partner",
          name: "Customer",
          technicalName: "partner_id",
          fieldType: "many2one",
          relation: "res.partner",
          accessByRole: fieldAccess("editable", "editable", "readonly", "readonly"),
        },
        {
          id: "order_amount",
          name: "Sales Amount",
          technicalName: "amount_total",
          fieldType: "monetary",
          accessByRole: fieldAccess("editable", "editable", "readonly", "readonly"),
        },
        {
          id: "order_margin",
          name: "Margin Rate",
          technicalName: "margin_percent",
          fieldType: "float",
          accessByRole: fieldAccess("hidden", "readonly", "readonly", "hidden"),
        },
        {
          id: "order_state",
          name: "State",
          technicalName: "state",
          fieldType: "selection",
          accessByRole: fieldAccess("readonly", "readonly", "readonly", "readonly"),
        },
      ],
    },
    {
      id: "invoice",
      name: "Customer Invoice",
      technicalName: "account.move",
      module: "Accounting",
      position: { x: 800, y: 48 },
      accessByRole: {
        sales: crud(true, false, false, false),
        manager: crud(true, false, false, false),
        finance: crud(true, true, true, true),
        warehouse: crud(false, false, false, false),
      },
      recordScopeByRole: {
        sales: "[('invoice_user_id', '=', user.id)]",
        manager: "[('invoice_user_id.team_id.member_ids', 'in', user.id)]",
        finance: "[('company_id', 'in', company_ids)]",
        warehouse: "[(0, '=', 1)]",
      },
      fields: [
        {
          id: "invoice_partner",
          name: "Customer",
          technicalName: "partner_id",
          fieldType: "many2one",
          relation: "res.partner",
          accessByRole: fieldAccess("readonly", "readonly", "editable", "hidden"),
        },
        {
          id: "invoice_amount",
          name: "Invoice Amount",
          technicalName: "amount_total",
          fieldType: "monetary",
          accessByRole: fieldAccess("readonly", "readonly", "editable", "hidden"),
        },
        {
          id: "invoice_payment",
          name: "Payment Status",
          technicalName: "payment_state",
          fieldType: "selection",
          accessByRole: fieldAccess("readonly", "readonly", "editable", "hidden"),
        },
      ],
    },
    {
      id: "picking",
      name: "Delivery Order",
      technicalName: "stock.picking",
      module: "Inventory",
      position: { x: 300, y: 365 },
      accessByRole: {
        sales: crud(true, false, false, false),
        manager: crud(true, false, false, false),
        finance: crud(false, false, false, false),
        warehouse: crud(true, true, true, false),
      },
      recordScopeByRole: {
        sales: "[('sale_id.user_id', '=', user.id)]",
        manager: "[('sale_id.team_id.member_ids', 'in', user.id)]",
        finance: "[(0, '=', 1)]",
        warehouse: "[('company_id', 'in', company_ids)]",
      },
      fields: [
        {
          id: "picking_origin",
          name: "Source Document",
          technicalName: "origin",
          fieldType: "char",
          accessByRole: fieldAccess("readonly", "readonly", "hidden", "readonly"),
        },
        {
          id: "picking_partner",
          name: "Delivery Address",
          technicalName: "partner_id",
          fieldType: "many2one",
          relation: "res.partner",
          accessByRole: fieldAccess("readonly", "readonly", "hidden", "editable"),
        },
        {
          id: "picking_state",
          name: "State",
          technicalName: "state",
          fieldType: "selection",
          accessByRole: fieldAccess("readonly", "readonly", "hidden", "editable"),
        },
      ],
    },
  ],
  workflow: {
    model: "sale.order",
    states: [
      { id: "draft", name: "Draft", technicalValue: "draft", x: 55, y: 150 },
      { id: "sent", name: "Quoted", technicalValue: "sent", x: 245, y: 150 },
      { id: "approval", name: "Pending Approval", technicalValue: "approval", x: 435, y: 150 },
      { id: "sale", name: "Confirmed", technicalValue: "sale", x: 625, y: 150 },
      { id: "done", name: "Done", technicalValue: "done", x: 815, y: 150 },
    ],
    transitions: [
      {
        id: "send_quote",
        name: "Send Quotation",
        from: "draft",
        to: "sent",
        allowedRoleIds: ["sales", "manager"],
        condition: "Order must contain at least one product line",
        actions: ["Send quotation email", "Record quotation time"],
      },
      {
        id: "request_approval",
        name: "Submit for Approval",
        from: "sent",
        to: "approval",
        allowedRoleIds: ["sales", "manager"],
        condition: "Order amount > 100000 or discount > 15%",
        actions: ["Create approval activity", "Notify sales manager"],
      },
      {
        id: "approve_order",
        name: "Approve Order",
        from: "approval",
        to: "sale",
        allowedRoleIds: ["manager"],
        condition: "Customer credit status is normal",
        actions: ["Lock sales price", "Create delivery order", "Notify warehouse"],
      },
      {
        id: "complete_order",
        name: "Complete Order",
        from: "sale",
        to: "done",
        allowedRoleIds: ["manager", "warehouse", "finance"],
        condition: "Delivery completed and invoice posted",
        actions: ["Write completion time"],
      },
    ],
  },
};
